project_name: diffusion-butterflies
logger_name: wandb
image_size: 128
train_batch_size: 16
eval_batch_size: 16
num_epochs: 50
dataset_name: huggan/smithsonian_butterflies_subset
gradient_accumulation_steps: 1
learning_rate: 0.0001
lr_warmup_steps: 500
save_image_epochs: 5
save_model_epochs: 5
mixed_precision: "no"
output_dir: ddpm-butterflies-128
overwrite_output_dir: true
seed: 0
num_train_timesteps: 1000