project_name: oxford-flowers
logger_name: wandb
image_size: 128
train_batch_size: 16
eval_batch_size: 16
num_epochs: 50
dataset_name: nelorth/oxford-flowers
huggingface_repo_name: anca-ioana/oxford-flowers
gradient_accumulation_steps: 1
learning_rate: 0.0001
lr_warmup_steps: 500
save_image_epochs: 5
save_model_epochs: 5
mixed_precision: "fp16"
output_dir: oxford-flowers
overwrite_output_dir: true
seed: 0
num_train_timesteps: 1000